ClinicalStudy.Site/Areas/DataCapture/Models/Patient/HeaderGroupViewModel.cs
namespace ClinicalStudy.Site.Areas.DataCapture.Models.Patient {
	public class HeaderGroupViewModel {
		public int PatientNumber { get; set; }
		public string PatientCaption { get; set; }
		public string ClinicCaption { get; set; }
		public string PatientInitials { get; set; }
		public string VisitName { get; set; }
		public string VisitDate { get; set; }
	}
}

ClinicalStudy.Site/Areas/DataCapture/Models/Patient/PatientLinkViewModel.cs
using System;
using System.Globalization;

namespace ClinicalStudy.Site.Areas.DataCapture.Models.Patient {
	public class PatientLinkViewModel {
		public int Id { get; set; }
		public string Caption { get; set; }
		public int PatientNumber { get; set; }


		public string DateOfBirth { get; set; }

		public string Sex { get; set; }

		public bool IsSelected { get; set; }

		public string Gender {
			get {
				if (Sex == null)
					return "Unknown";

				return Sex == "0" ? "Male" : "Female";
			}
		}

		public string Age {
			get {
				if (DateOfBirth == null)
					return "Unknown";
				DateTime date = DateTime.Parse(DateOfBirth, CultureInfo.InvariantCulture);
				return string.Format("Age {0}", Math.Truncate(DateTime.Now.Subtract(date).TotalDays/365));
			}
		}
	}
}

ClinicalStudy.Site/Areas/DataCapture/Models/Patient/PatientsListViewModel.cs
using System.Collections.Generic;

namespace ClinicalStudy.Site.Areas.DataCapture.Models.Patient {
	public class PatientsListViewModel {
		public List<PatientLinkViewModel> PatientsList { get; set; }
		public bool CertainPatientRequested { get; set; }
		public int CertainPatientPageIndex { get; set; }
		public bool CertainPatientIsActive { get; set; }
	}
}

ClinicalStudy.Site/Areas/DataCapture/Models/PatientViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace ClinicalStudy.Site.Areas.DataCapture.Models {
	public class PatientViewModel {
		public int Id { get; set; }
		public string Caption { get; set; }
		public int PatientNumber { get; set; }
		public bool IsActive { get; set; }

		public bool IsEnrolled { get; set; }

		public DateTime? EnrollDate { get; set; }

		[Required(ErrorMessage = "Please enter Patient Initials")]
		[StringLength(3, MinimumLength = 2, ErrorMessage = "Please specify First and Last Name Initials")]
		public string PatientInitials { get; set; }

		public int? RandomisationNumber { get; set; }

		public DateTime? RandomisationDate { get; set; }


		public bool IsNewPatient {
			get { return Id == 0; }
		}
	}
}

ClinicalStudy.Site/Areas/DataCapture/Controllers/PatientController.cs
using System.Collections.Generic;
using System.Linq;
using System.Security;
using System.Web.Mvc;
using ClinicalStudy.DomainModel;
using ClinicalStudy.DomainModel.Enums;
using ClinicalStudy.DomainModel.FormData;
using ClinicalStudy.DomainModel.ModelBuilders;
using ClinicalStudy.Repositories.Interface;
using ClinicalStudy.Repositories.Interface.FormData;
using ClinicalStudy.Site.Areas.DataCapture.Models;
using ClinicalStudy.Site.Areas.DataCapture.Models.Patient;
using ClinicalStudy.Site.Areas.DataCapture.Models.Shared;
using DevExpress.Web.Mvc;

namespace ClinicalStudy.Site.Areas.DataCapture.Controllers {
	public class PatientController : DataCaptureBaseController {
		private readonly IClinicalStudyDesignFactory clinicalStudyDesignFactory;
		private readonly IDemographicFormDataRepository demographicFormDataRepository;
		private readonly IPatientRepository patientRepository;
		private readonly IUserRepository userRepository;

		public PatientController(IUserRepository userRepository,
		                         IPatientRepository patientRepository,
		                         IDemographicFormDataRepository demographicFormDataRepository,
		                         IClinicalStudyDesignFactory clinicalStudyDesignFactory) {
			this.userRepository = userRepository;
			this.patientRepository = patientRepository;
			this.demographicFormDataRepository = demographicFormDataRepository;
			this.clinicalStudyDesignFactory = clinicalStudyDesignFactory;
		}

		public ActionResult PatientHeaderGroup(int patientNumber, string visitName) {
			Patient patient = patientRepository.GetPatientByUniqueNumber(patientNumber);
			HeaderGroupViewModel model = GetHeaderModel(patient, visitName);


			return PartialView("_PatientHeaderGroup", model);
		}

		private HeaderGroupViewModel GetHeaderModel(Patient patient, string visitName) {
			HeaderGroupViewModel model;
			if (patient == null) {
				model = new HeaderGroupViewModel {PatientCaption = "New Patient"};
			}
			else {
				model = new HeaderGroupViewModel {
					PatientNumber = patient.PatientNumber,
					PatientCaption = patient.Caption,
					PatientInitials = patient.PatientInitials,
					ClinicCaption = patient.Doctor.Clinic.Caption,
					VisitName = visitName
				};
			}
			return model;
		}

		public ActionResult PatientGrid(int? patientNumber = null, string activityState = null, bool needFindPatient = false,
		                                int pageSize = 8) {
			User doctor = userRepository.GetUserByLogin(User.Identity.Name);
			if (doctor == null)
				return null;

			int selectedPatientNumber = patientNumber ?? -1;
			if (RouteData.Values["patientNumber"] != null) {
				int.TryParse(RouteData.Values["patientNumber"].ToString(), out selectedPatientNumber);
			}
			bool patientActivityState = true;
			if (string.Equals("inactive", activityState))
				patientActivityState = false;

			if (needFindPatient && selectedPatientNumber > 0) {
				Patient pat = patientRepository.GetPatientByUniqueNumber(selectedPatientNumber);
				if (pat != null) {
					patientActivityState = pat.IsActive;
				}
			}

			var formDataQuery = from formData in demographicFormDataRepository.GetAll()
			                                                select formData;

			var patients = (from patient in patientRepository.GetAll()
			                                       from visit in patient.Visits
			                                       from form in visit.Forms
			                                       from formData in formDataQuery
			                                       where patient.Doctor.Id == doctor.Id
			                                             && visit.VisitTypeValue == (int) VisitType.Baseline
			                                             && form.FormTypeValue == (int) FormType.Demographics
			                                             && form.Id == formData.Form.Id
			                                             && patient.IsActive == patientActivityState
			                                       orderby patient.Caption descending
			                                       select new PatientLinkViewModel {
			                                       	Id = patient.Id,
			                                       	Caption = patient.Caption,
			                                       	PatientNumber = patient.PatientNumber,
			                                       	Sex = formData.Sex.Value,
			                                       	DateOfBirth = formData.DateOfBirth.Value,
			                                       	IsSelected = patient.PatientNumber == selectedPatientNumber
			                                       }).ToList();

			var model = new PatientsListViewModel {
				PatientsList = patients,
				CertainPatientRequested = needFindPatient,
				CertainPatientIsActive = patientActivityState,
				CertainPatientPageIndex =
					needFindPatient ? (patients.FindIndex(x => x.PatientNumber == selectedPatientNumber)/pageSize) : -1
			};

			return PartialView("_PatientGrid", model);
		}

		public ActionResult PatientDataContainer(int patientNumber, string visitName, string formName) {
			DataContainerViewModel model = CreatePatientDataModel(patientNumber, visitName, formName);
			if (model == null) {
				throw new SecurityException("Unauthorized access to patient's data");
			}

			if (Request.IsAjaxRequest())
				return PartialView("_PatientDataContainer", model);
			return View(model);
		}

		private DataContainerViewModel CreatePatientDataModel(int patientNumber, string visitName, string formName) {
			Patient patient = patientRepository.GetPatientByUniqueNumber(patientNumber);
			if (patient == null)
				return new DataContainerViewModel {
					Id = 0,
					PatientNumber = patientRepository.GetMaxPatientNumber() + 1,
					Children = new List<ConteinerChildViewModel>()
				};

			if (patient.Doctor.Login != User.Identity.Name)
				return null;

			var model = new DataContainerViewModel {
				Id = patient.Id,
				PatientCaption = patient.Caption,
				PatientNumber = patient.PatientNumber,
				PatientInitials = patient.PatientInitials,
				SelectedVisitName = visitName,
				SelectedFormName = formName,
				Children = new List<ConteinerChildViewModel>(
					from v in patient.Visits
					orderby v.OrderNo
					select new ConteinerChildViewModel {
						Id = v.Id,
						Caption = v.Caption,
						OrderNo = v.OrderNo
					}
					)
			};
			return model;
		}

		public ActionResult PatientDataPages(int patientNumber, string visitName, string formName) {
			DataContainerViewModel model = CreatePatientDataModel(patientNumber, visitName, formName);
			return PartialView("_PatientDataPages", model);
		}

		public ActionResult PatientDataPanel(int patientNumber, string visitName, string formName) {
			DataContainerViewModel model = CreatePatientDataModel(patientNumber, visitName, formName);
			return PartialView("_PatientDataPagesPanel", model);
		}

		public ActionResult CreatePatient() {
			int maxNumber = patientRepository.GetMaxPatientNumber();
			var model = new PatientViewModel {
				Id = 0,
				PatientNumber = maxNumber + 1,
                Caption = "New Patient",
				IsActive = true
			};

			return PartialView("_EditPatient", model);
		}

		public ActionResult ShowPatient(int patientNumber) {
			return ViewEditPatient(null, patientNumber);
		}

		public ActionResult ViewPatient(int patientNumber) {
			return ViewEditPatient(false, patientNumber);
		}

		public ActionResult EditPatient(int patientNumber) {
			return ViewEditPatient(true, patientNumber);
		}

		public ActionResult ViewEditPatient(bool? isPatientEditing, int patientNumber) {
			Patient patient = patientRepository.GetPatientByUniqueNumber(patientNumber);

			if (patient == null) {
				return RedirectToAction("CreatePatient");
			}

			var model = new PatientViewModel {
				Id = patient.Id,
				Caption = patient.Caption,
				PatientNumber = patient.PatientNumber,
				EnrollDate = patient.EnrollDate,
				IsActive = patient.IsActive,
				IsEnrolled = patient.IsEnrolled,
				PatientInitials = patient.PatientInitials,
				RandomisationDate = patient.RandomisationDate,
				RandomisationNumber = patient.RandomisationNumber
			};


			if (patient.IsCompleted && !(isPatientEditing ?? false))
				return PartialView("_ViewPatient", model);
			return PartialView("_EditPatient", model);
		}


		[HttpPost]
		public ActionResult EditPatient([ModelBinder(typeof (DevExpressEditorsBinder))] PatientViewModel model) {
			Patient patient = patientRepository.GetByKey(model.Id);
			if (patient == null) {
				IClinicalStudyDesign studyDesign = clinicalStudyDesignFactory.Create();
				patient = studyDesign.CreatePatientForDoctor(User.Identity.Name);
				clinicalStudyDesignFactory.Release(studyDesign);
			}
			patient.IsActive = model.IsActive;
			patient.IsEnrolled = model.IsEnrolled;
			patient.EnrollDate = model.EnrollDate;
			patient.PatientInitials = model.PatientInitials;
			patient.RandomisationNumber = model.RandomisationNumber;
			patient.RandomisationDate = model.RandomisationDate;
			patient.IsCompleted = true;
			patientRepository.Edit(patient);
			patientRepository.Save();

			return RedirectToAction("ShowPatient", new {patientNumber = patient.PatientNumber, DXScript = Request["DXScript"]});
		}
	}
}

ClinicalStudy.Site/Areas/DataCapture/Controllers/VisitController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using ClinicalStudy.DomainModel;
using ClinicalStudy.DomainModel.Enums;
using ClinicalStudy.DomainModel.ModelBuilders;
using ClinicalStudy.Repositories.Interface;
using ClinicalStudy.Site.Areas.DataCapture.Models;
using ClinicalStudy.Site.Areas.DataCapture.Models.Shared;
using DevExpress.Web.Mvc;

namespace ClinicalStudy.Site.Areas.DataCapture.Controllers {
	public class VisitController : DataCaptureBaseController {
		private readonly IClinicalStudyDesignFactory clinicalStudyDesignFactory;
		private readonly IVisitRepository visitRepository;

		public VisitController(IVisitRepository visitRepository, IClinicalStudyDesignFactory clinicalStudyDesignFactory) {
			this.visitRepository = visitRepository;
			this.clinicalStudyDesignFactory = clinicalStudyDesignFactory;
		}

		public ActionResult VisitDataContainer(int patientNumber, string visitName, string formName) {
			DataContainerViewModel model = CreateVisitDataModel(patientNumber, visitName, formName);

			return PartialView("_VisitDataContainer", model);
		}

		private DataContainerViewModel CreateVisitDataModel(int patientNumber, string visitName, string formName) {
			Visit visit = visitRepository.GetVisitByPatientNumberAndVisitName(patientNumber, visitName);
			if (visit == null)
				return null;

			var model = new DataContainerViewModel {
				Id = visit.Id,
				PatientNumber = patientNumber,
				SelectedVisitName = visitName,
				SelectedFormName = formName,
				Children = new List<ConteinerChildViewModel>(from form in visit.Forms
				                                             orderby form.OrderNo
				                                             select new ConteinerChildViewModel {
				                                             	Id = form.Id,
				                                             	Caption = form.Caption,
				                                             	OrderNo = form.OrderNo
				                                             })
			};
			return model;
		}


		public ActionResult ShowVisit(int patientNumber, string visitName) {
			return ViewEditVisit(null, patientNumber, visitName);
		}

		public ActionResult ViewVisit(int patientNumber, string visitName) {
			return ViewEditVisit(false, patientNumber, visitName);
		}

		public ActionResult EditVisit(int visitId) {
			return ViewEditVisit(true, visitId);
		}

		public ActionResult ViewEditVisit(bool? isVisitEditing, int visitId) {
			Visit visit = visitRepository.GetByKey(visitId);
			return ViewEditVisit(isVisitEditing, visit);
		}

		public ActionResult ViewEditVisit(bool? isVisitEditing, int patientNumber, string visitName) {
			Visit visit = visitRepository.GetVisitByPatientNumberAndVisitName(patientNumber, visitName);
			return ViewEditVisit(isVisitEditing, visit);
		}


		private ActionResult ViewEditVisit(bool? isVisitEditing, Visit visit) {
			if (visit == null) {
				var errorModel = new ErrorViewModel {
					Caption = "Visit is not found",
					ErrorMessage = string.Format("Visit is not found in clinical data")
				};
				return View("ErrorInfo", errorModel);
			}

			var model = new VisitViewModel {
				Id = visit.Id,
				Caption = visit.Caption,
				VisitType = visit.VisitType,
				ExpectedVisitDate = visit.ExpectedVisitDate,
				VisitDate = visit.VisitDate,
				VisitTime = visit.VisitTime,
				OrderNo = visit.OrderNo,
				NoExpectedVisitDate = visit.VisitType == VisitType.AdverseEventVisit
			};

			if (visit.IsCompleted && !(isVisitEditing ?? false))
				return PartialView("_ViewVisit", model);
			return PartialView("_EditVisit", model);
		}

		[HttpPost]
		public ActionResult EditVisit([ModelBinder(typeof (DevExpressEditorsBinder))] VisitViewModel model) {
			Visit visit = visitRepository.GetByKey(model.Id);
			if (visit == null) {
				var errorModel = new ErrorViewModel {
					Caption = "Visit is not found",
					ErrorMessage = string.Format("Visit '{0}' is not found in clinical data", model.Caption)
				};
				return View("ErrorInfo", errorModel);
			}

			visit.Caption = model.Caption;
			visit.ExpectedVisitDate = model.ExpectedVisitDate;
			visit.VisitDate = model.VisitDate;
			visit.VisitTime = model.VisitTime;
			EnsureSqlServer2005Compatibility(visit);
			if (visit.VisitDate.HasValue && visit.VisitTime.HasValue)
				visit.IsCompleted = true;
			visitRepository.Edit(visit);
			visitRepository.Save();

			return RedirectToAction("ShowVisit",
				new {
					patientNumber = visit.Patient.PatientNumber,
					visitName = visit.Caption,
					DXScript = Request["DXScript"]
				});
		}

		public ActionResult CreateAdverseEvent(int patientId) {
			IClinicalStudyDesign studyDesign = clinicalStudyDesignFactory.Create();

			Visit aeVisit = studyDesign.AddAdverseEventVisit(patientId);
			clinicalStudyDesignFactory.Release(studyDesign);


			if (aeVisit == null)
				return null;


			return Content(aeVisit.Caption);
		}

		private static void EnsureSqlServer2005Compatibility(Visit visit) {
			if (visit.VisitTime.HasValue && visit.VisitTime.Value.Year <= 1753)
				visit.VisitTime = visit.VisitTime.Value.AddYears(DateTime.Now.Year);
		}
	}
}

ClinicalStudy.Site/Areas/DataCapture/Views/Patient/PatientDataContainer.cshtml
@model ClinicalStudy.Site.Areas.DataCapture.Models.Shared.DataContainerViewModel
@{
	ViewBag.Title = Model.PageTitle;
	Layout = "~/Areas/DataCapture/Views/Shared/_DataCaptureLayout.cshtml";
}
@Html.Partial("_PatientDataContainer")

ClinicalStudy.Site/Areas/DataCapture/Views/Patient/_EditPatient.cshtml
@model ClinicalStudy.Site.Areas.DataCapture.Models.PatientViewModel
@{
	string validationGroup = string.Format("patient{0}Validation", Model.Id);
}   
<div id="patientPanel">
	<h2>Patient Information - @Model.Caption</h2>
	@using (Ajax.BeginForm("EditPatient", "Patient",
		null,
		new AjaxOptions {
			UpdateTargetId = "patientPanel",
			LoadingElementId = "loadingIndicator",
			OnSuccess = "refreshPatientListAfterEdit",
			OnFailure = "ajaxFailure"
		},
		new {id = "editPatientForm"})) {
		@Html.HiddenFor(model => model.Id)

		<div class="editor-field">
			@Html.DevExpress().Label(s => {
		                               	s.Text = "Patient Initials:";
		                               	s.ControlStyle.CssClass = "editor-label";
		                               	s.AssociatedControlName = "PatientInitials";
		                               }).GetHtml()
			@Html.DevExpress().TextBox(s => {
		                                 	s.Name = "PatientInitials";
		                                 	s.Width = 150;
                                            s.ShowModelErrors = true;
                                            s.Properties.ValidationSettings.ValidationGroup = validationGroup;
		                                 	s.Properties.ValidationSettings.ErrorDisplayMode = ErrorDisplayMode.ImageWithText;
		                                 }).Bind(Model.PatientInitials).GetHtml()
		</div>

		<div class="editor-field">
			@Html.HiddenFor(m => m.PatientNumber)
			@Html.DevExpress().Label(s => {
		                               	s.Text = "Patient Number:";
		                               	s.ControlStyle.CssClass = "editor-label";
		                               	s.AssociatedControlName = "PatientNumber";
		                               }).GetHtml()
			@Html.DevExpress().Label(s => { s.Width = 150; }).Bind(Model.PatientNumber).GetHtml()
		</div>

		<div class="editor-field">
			@Html.DevExpress().Label(s => {
		                               	s.Text = "Active:";
		                               	s.ControlStyle.CssClass = "editor-label";
		                               	s.AssociatedControlName = "IsActive";
		                               }).GetHtml()
			@Html.DevExpress().CheckBox(s => {
		                                  	s.Name = "IsActive";
                                            s.Width = 150;
                                            s.Properties.ValidationSettings.ValidationGroup = validationGroup;
		                                  }).Bind(Model.IsActive).GetHtml()
		</div>

		<div class="editor-field">
			@Html.DevExpress().Label(s => {
		                               	s.Text = "Enrolled:";
		                               	s.ControlStyle.CssClass = "editor-label";
		                               	s.AssociatedControlName = "IsEnrolled";
		                               }).GetHtml()
			@Html.DevExpress().CheckBox(s => {
		                                  	s.Name = "IsEnrolled";
                                            s.Width = 150;
                                            s.Properties.ValidationSettings.ValidationGroup = validationGroup;
		                                  }).Bind(Model.IsEnrolled).GetHtml()
		</div>

		<div class="editor-field">
			@Html.DevExpress().Label(s => {
		                               	s.Text = "Enroll Date:";
		                               	s.ControlStyle.CssClass = "editor-label";
		                               	s.AssociatedControlName = "EnrollDate";
		                               }).GetHtml()
			@Html.DevExpress().DateEdit(s => {
		                                  	s.Name = "EnrollDate";
                                            s.Width = 150;
                                            s.Properties.ValidationSettings.ValidationGroup = validationGroup;
		                                  }).Bind(Model.EnrollDate).GetHtml()
		</div>

		<div class="editor-field">
			@Html.DevExpress().Label(s => {
		                               	s.Text = "Randomization Number:";
		                               	s.ControlStyle.CssClass = "editor-label";
		                               	s.AssociatedControlName = "RandomisationNumber";
		                               }).GetHtml()
			@Html.DevExpress().SpinEdit(s => {
		                                  	s.Name = "RandomisationNumber";
                                            s.Width = 150;
                                            s.Properties.ValidationSettings.ValidationGroup = validationGroup;
		                                  }).Bind(Model.RandomisationNumber).GetHtml()
		</div>

		<div class="editor-field">
			@Html.DevExpress().Label(s => {
		                               	s.Text = "Randomization Date:";
		                               	s.ControlStyle.CssClass = "editor-label";
		                               	s.AssociatedControlName = "RandomisationDate";
		                               }).GetHtml()
			@Html.DevExpress().DateEdit(s => {
		                                  	s.Name = "RandomisationDate";
                                            s.Width = 150;
                                            s.Properties.ValidationSettings.ValidationGroup = validationGroup;
		                                  }).Bind(Model.RandomisationDate).GetHtml()
		</div>

		@Html.DevExpress().Button(s => {
		                                	s.Name = "btnSave";
		                                	s.Text = "Save";
		                                	s.SkinID = "DarkPink";
		                                	s.UseSubmitBehavior = true;
		                                	s.ValidationGroup = validationGroup;
		                                	s.ClientSideEvents.Click = "function(s,e){ PrepareValidationScripts($('#editPatientForm'));}";
		                                }).GetHtml()
	}

</div>

ClinicalStudy.Site/Areas/DataCapture/Views/Patient/_HeaderPanelCallback.cshtml
@model ClinicalStudy.Site.Areas.DataCapture.Models.Patient.HeaderGroupViewModel
<h1>@Model.PatientCaption</h1>
@if (!string.IsNullOrWhiteSpace(Model.ClinicCaption)) {
	@Html.DevExpress().Label(s => {
	                               	s.Text = "Clinic: " + Model.ClinicCaption;
	                               	s.SkinID = "SmallLabel";
	                               	s.Style.Add("color", "#6b636b");
	                               	s.Style.Add("margin", "0 0 5px 0");
	                               	s.Style.Add("display", "block");
	                               }).GetHtml()
}
@if (!string.IsNullOrWhiteSpace(Model.PatientInitials)) {
	@Html.DevExpress().Label(s => {
	                               	s.Text = "Patient Initials: ";
	                               	s.SkinID = "SmallLabel";
	                               	s.Style.Add("color", "#6b636b");
	                               	s.Style.Add("margin", "0 0 5px 0");
	                               	//s.Style.Add("display", "block");
	                               }).GetHtml()

	@Html.DevExpress().Label(s => {
	                               	s.Text = Model.PatientInitials;
	                               	s.Name = "HeaderPatientInitialsLabel";
	                               	s.SkinID = "SmallLabel";
	                               	s.Style.Add("color", "#6b636b");
	                               	s.Style.Add("margin", "0 0 5px 0");
	                               	//s.Style.Add("display", "block");
	                               }).GetHtml()
}

ClinicalStudy.Site/Areas/DataCapture/Views/Patient/_PatientDataContainer.cshtml
@model ClinicalStudy.Site.Areas.DataCapture.Models.Shared.DataContainerViewModel

<div class="patientDataContainer">
	<div class="headerGroup" data-page-title="@(Model.PageTitle)">
		@Html.Action("PatientHeaderGroup", "Patient", new {patientNumber = Model.PatientNumber, visitName = Model.SelectedVisitName})
	</div> 
	@Html.Partial("_PatientDataPagesPanel")
</div>

ClinicalStudy.Site/Areas/DataCapture/Views/Patient/_PatientDataPages.cshtml
@using System.Web.UI.WebControls
@using ClinicalStudy.Site.Areas.DataCapture.HtmlHelpers
@using ClinicalStudy.Site.Areas.DataCapture.Models.Shared
@model ClinicalStudy.Site.Areas.DataCapture.Models.Shared.DataContainerViewModel
@Html.DevExpress().TabControl(
	s => {
		s.Name = "PatientVisitsTabt";
		s.Width = Unit.Percentage(100);
		s.EnableTabScrolling = true;
		s.TabAlign = TabAlign.Center;

		s.CustomJSProperties = (sender, e) => {
		                       	e.Properties.Add("cpPageTitle", Model.PageTitle);
		                       	e.Properties.Add("cpPatientInitials", Model.PatientInitials);
		                       };

		s.Tabs.Add("Summary", "Summary");


		foreach (ConteinerChildViewModel visit in Model.Children) {
			s.Tabs.Add(visit.Caption, visit.Caption);
		}


		if (!string.IsNullOrEmpty(Model.SelectedVisitName)) {
			int index = Model.Children.FindIndex(v => v.Caption == Model.SelectedVisitName);
			if (index != -1)
				s.ActiveTabIndex = index + 1;
		}

		s.ClientSideEvents.TabClick = "OnVisitTabClick";
		s.ClientSideEvents.EndCallback = "afterPatientPanelLoaded";
	}
	).GetHtml()
<div class="tabsContent">
	@if (string.IsNullOrWhiteSpace(Model.SelectedVisitName) || Model.SelectedVisitName.Equals("Summary", StringComparison.InvariantCultureIgnoreCase)) {
		if (Model.IsNew) {
			Html.RenderAction("CreatePatient", "Patient");
		}
		else {
			Html.RenderAction("ShowPatient", "Patient", new {patientNumber = Model.PatientNumber});
		}
	}
	else {
		Html.RenderAction("VisitDataContainer", "Visit", new {patientNumber = Model.PatientNumber, visitName = Model.SelectedVisitName});
	}
</div>
@if (!Model.IsNew) {
	@Ajax.ImageActionLink(Url.Content("~/Content/Icons/AddNewTab.png"),
		"Add Adverse Event",
		"CreateAdverseEvent",
		"Visit",
		new {patientId = Model.Id, irt = DateTime.Now.Ticks},
		new AjaxOptions {
			LoadingElementId = "loadingIndicator",
			OnSuccess = "showCreatedAdverseEvent"
		},
		new {@class = "addNewAE", title = "Add Adverse Event. Record diagnoses (if known) or signs/symptoms the participant/subject experienced during the study that qualify as adverse events."})
}
<script type="text/javascript">
    if (window.selectedStudyData) {
        window.selectedStudyData.selectedPatientNumber = @Model.PatientNumber;
        window.selectedStudyData.selectedVisitName = @(Html.Raw(string.IsNullOrEmpty(Model.SelectedVisitName) ? "'Summary'" : string.Format("'{0}'", Model.SelectedVisitName)));
    }
</script>

ClinicalStudy.Site/Areas/DataCapture/Views/Patient/_PatientHeaderGroup.cshtml
@model ClinicalStudy.Site.Areas.DataCapture.Models.Patient.HeaderGroupViewModel
		   
@Html.Partial("_HeaderPanelCallback")