ClinicalStudy.Site/Areas/DataCapture/Models/VisitViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using ClinicalStudy.DomainModel.Enums;

namespace ClinicalStudy.Site.Areas.DataCapture.Models {
	public class VisitViewModel {
		public int Id { get; set; }
		public string Caption { get; set; }
		public DateTime? VisitDate { get; set; }
		public DateTime? VisitTime { get; set; }

		[Required]
		public DateTime? ExpectedVisitDate { get; set; }

		public VisitType VisitType { get; set; }
		public int OrderNo { get; set; }

		public bool NoExpectedVisitDate { get; set; }
	}
}

ClinicalStudy.Site/Areas/DataCapture/Controllers/FormController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.Linq;
using System.Web.Mvc;
using System.Web.Routing;
using ClinicalStudy.DomainModel;
using ClinicalStudy.DomainModel.Enums;
using ClinicalStudy.DomainModel.Enums.Answers;
using ClinicalStudy.DomainModel.Enums.Display;
using ClinicalStudy.DomainModel.FormData;
using ClinicalStudy.DomainModel.ModelBuilders;
using ClinicalStudy.Repositories.Interface;
using ClinicalStudy.Repositories.Interface.FormData;
using ClinicalStudy.Site.Areas.DataCapture.ControlHelper;
using ClinicalStudy.Site.Areas.DataCapture.Models;
using ClinicalStudy.Site.Areas.DataCapture.Models.FormData;
using ClinicalStudy.Site.Areas.DataCapture.Models.Query;
using ClinicalStudy.Site.Areas.DataCapture.Models.Shared;
using DevExpress.Web.ASPxHtmlEditor;
using DevExpress.Web.Mvc;

namespace ClinicalStudy.Site.Areas.DataCapture.Controllers {
	public class FormController : DataCaptureBaseController {
		public const string ChangeNoteRequest = "Please specify the Change Reason for every data change you have made";
		private readonly IAdverseEventFormDataRepository adverseEventFormDataRepository;
		private readonly IAttachmentRepository attachmentRepository;
		private readonly IChangeNoteBuilder changeNoteBuilder;
		private readonly IDemographicFormDataRepository demographicFormDataRepository;
		private readonly IElectrocardiogramFormDataRepository electrocardiogramFormDataRepository;
		private readonly IFormRepository formRepository;
		private readonly IHappinessFormDataRepository happinessFormDataRepository;
		private readonly IInventoryFormDataRepository inventoryFormDataRepository;
		private readonly IQueryRepository queryRepository;
		private readonly IVitalsFormDataRepository vitalsFormDataRepository;

		public FormController(IFormRepository formRepository,
		                      IDemographicFormDataRepository demographicFormDataRepository,
		                      IVitalsFormDataRepository vitalsFormDataRepository,
		                      IHappinessFormDataRepository happinessFormDataRepository,
		                      IElectrocardiogramFormDataRepository electrocardiogramFormDataRepository,
		                      IInventoryFormDataRepository inventoryFormDataRepository,
		                      IAdverseEventFormDataRepository adverseEventFormDataRepository,
		                      IAttachmentRepository attachmentRepository,
		                      IQueryRepository queryRepository,
		                      IChangeNoteBuilder changeNoteBuilder = null) {
			this.formRepository = formRepository;
			this.demographicFormDataRepository = demographicFormDataRepository;
			this.vitalsFormDataRepository = vitalsFormDataRepository;
			this.happinessFormDataRepository = happinessFormDataRepository;
			this.electrocardiogramFormDataRepository = electrocardiogramFormDataRepository;
			this.inventoryFormDataRepository = inventoryFormDataRepository;
			this.adverseEventFormDataRepository = adverseEventFormDataRepository;
			this.attachmentRepository = attachmentRepository;
			this.queryRepository = queryRepository;
			this.changeNoteBuilder = changeNoteBuilder;
			HtmlEditorAdapter = new HtmlEditorAdapter();
		}

		public IHtmlEditorAdapter HtmlEditorAdapter { get; set; }

		public ActionResult EditForm(int patientNumber, string visitName, string formName) {
			return ViewEditForm(true, patientNumber, visitName, formName);
		}

		public ActionResult ViewForm(int patientNumber, string visitName, string formName) {
			return ViewEditForm(false, patientNumber, visitName, formName);
		}


		public ActionResult ShowForm(int patientNumber, string visitName, string formName) {
			return ViewEditForm(null, patientNumber, visitName, formName);
		}

		[HttpPost]
		public ActionResult EditDemographicForm(
			[ModelBinder(typeof (DevExpressEditorsBinder))] DemographicFormViewModel viewModel) {
			if (!ModelState.IsValid)
				return PartialView("_EditDemographicForm", viewModel);


			Form form = formRepository.GetByKey(viewModel.FormId);
			if (form == null)
				return ComposeErrorInfoView(viewModel.FormCaption, viewModel.FormId);

			DemographicFormData formData = demographicFormDataRepository.GetByKey(viewModel.Id);
			if (formData == null)
				return ComposeErrorInfoView(viewModel.FormCaption, viewModel.FormId);


			if (form.FormState == FormState.Completed) {
				viewModel.IsCompleted = true;
				CheckDemograpihcFormChangeReasons(viewModel, formData);
				if (viewModel.DataChangeReasonRequired) {
					ModelState.AddModelError(string.Empty, ChangeNoteRequest);
					return PartialView("_EditDemographicForm", viewModel);
				}
			}

			MapDemographicViewModelToFormData(viewModel, formData);
			SaveFormDataChangeReasons(viewModel, formData);
			demographicFormDataRepository.Edit(formData);
			demographicFormDataRepository.Save();

			return SaveFormAsCompletedAndRedirect(form);
		}


		private static void CheckDemograpihcFormChangeReasons(DemographicFormViewModel viewModel, DemographicFormData formData) {
			Debug.Assert(viewModel.DateOfBirth.HasValue);

			if (viewModel.ChangeInfos == null)
				viewModel.ChangeInfos = new List<ChangeNoteViewModel>();

			int oldRaceId;
			int.TryParse(formData.Race.Value, out oldRaceId);
			int oldSexId;
			int.TryParse(formData.Sex.Value, out oldSexId);
			DateTime originalDateOfBirth;
			DateTime.TryParse(formData.DateOfBirth.Value, out originalDateOfBirth);

			AddChangeReasonRequestIfRequired(formData.DateOfBirth, originalDateOfBirth.ToShortDateString(),
				viewModel.DateOfBirth.Value.ToShortDateString(), viewModel.ChangeInfos);
			AddChangeReasonRequestIfRequired(formData.Race, EnumHelper.GetDescription((Race) oldRaceId),
				EnumHelper.GetDescription((Race) viewModel.Race), viewModel.ChangeInfos);
			AddChangeReasonRequestIfRequired(formData.Sex, EnumHelper.GetDescription((Gender) oldSexId),
				EnumHelper.GetDescription((Gender) viewModel.Sex), viewModel.ChangeInfos);
			AddChangeReasonRequestIfRequired(formData.Other, formData.Other.Value, viewModel.Other, viewModel.ChangeInfos);

			if (viewModel.ChangeInfos.Any(ci => string.IsNullOrWhiteSpace(ci.ChangeReason)))
				viewModel.DataChangeReasonRequired = true;
		}


		[HttpPost]
		public ActionResult EditVitalsForm([ModelBinder(typeof (DevExpressEditorsBinder))] VitalsFormViewModel viewModel) {
			if (!ModelState.IsValid)
				return PartialView("_EditVitalsForm", viewModel);

			Form form = formRepository.GetByKey(viewModel.FormId);
			if (form == null)
				return ComposeErrorInfoView(viewModel.FormCaption, viewModel.FormId);

			VitalsFormData formData = vitalsFormDataRepository.GetByKey(viewModel.Id);
			if (formData == null)
				return ComposeErrorInfoView(viewModel.FormCaption, viewModel.FormId);

			if (form.FormState == FormState.Completed) {
				viewModel.IsCompleted = true;
				CheckVitalsFormChangeReasons(viewModel, formData);
				if (viewModel.DataChangeReasonRequired) {
					ModelState.AddModelError(string.Empty, ChangeNoteRequest);
					return PartialView("_EditVitalsForm", viewModel);
				}
			}

			MapVitalsViewModelToFormData(viewModel, formData);
			SaveFormDataChangeReasons(viewModel, formData);
			vitalsFormDataRepository.Edit(formData);
			vitalsFormDataRepository.Save();

			return SaveFormAsCompletedAndRedirect(form);
		}

		private void CheckVitalsFormChangeReasons(VitalsFormViewModel viewModel, VitalsFormData formData) {
			Debug.Assert(viewModel.ActualTime.HasValue);

			if (viewModel.ChangeInfos == null)
				viewModel.ChangeInfos = new List<ChangeNoteViewModel>();

			DateTime originalActualTime;
			DateTime.TryParse(formData.ActualTime.Value, out originalActualTime);

			AddChangeReasonRequestIfRequired(formData.ActualTime, originalActualTime.ToShortTimeString(),
				viewModel.ActualTime.Value.ToShortTimeString(), viewModel.ChangeInfos);
			AddChangeReasonRequestIfRequired(formData.Weight, formData.Weight.Value, viewModel.Weight.ToString(),
				viewModel.ChangeInfos);
			AddChangeReasonRequestIfRequired(formData.Height, formData.Height.Value, viewModel.Height.ToString(),
				viewModel.ChangeInfos);
			AddChangeReasonRequestIfRequired(formData.HeartRate, formData.HeartRate.Value, viewModel.HeartRate.ToString(),
				viewModel.ChangeInfos);
			AddChangeReasonRequestIfRequired(formData.Temperature, formData.Temperature.Value, viewModel.Temperature.ToString(),
				viewModel.ChangeInfos);
			AddChangeReasonRequestIfRequired(formData.BloodPressureSystolic, formData.BloodPressureSystolic.Value,
				viewModel.BloodPressureSystolic, viewModel.ChangeInfos);
			AddChangeReasonRequestIfRequired(formData.BloodPressureDiastolic, formData.BloodPressureDiastolic.Value,
				viewModel.BloodPressureDiastolic, viewModel.ChangeInfos);

			if (viewModel.ChangeInfos.Any(ci => string.IsNullOrWhiteSpace(ci.ChangeReason)))
				viewModel.DataChangeReasonRequired = true;
		}

		[HttpPost]
		public ActionResult EditHappinessForm([ModelBinder(typeof (DevExpressEditorsBinder))] HappinessFormViewModel viewModel) {
			if (!ModelState.IsValid)
				return PartialView("_EditHappinessForm", viewModel);

			Form form = formRepository.GetByKey(viewModel.FormId);
			if (form == null)
				return ComposeErrorInfoView(viewModel.FormCaption, viewModel.FormId);

			HappinessFormData formData = happinessFormDataRepository.GetByKey(viewModel.Id);
			if (formData == null)
				return ComposeErrorInfoView(viewModel.FormCaption, viewModel.FormId);

			if (form.FormState == FormState.Completed) {
				viewModel.IsCompleted = true;
				CheckHappinessFormChangeReasons(viewModel, formData);
				if (viewModel.DataChangeReasonRequired) {
					ModelState.AddModelError(string.Empty, ChangeNoteRequest);
					return PartialView("_EditHappinessForm", viewModel);
				}
			}


			MapHappinessViewModelToFormData(viewModel, formData);
			SaveFormDataChangeReasons(viewModel, formData);
			happinessFormDataRepository.Edit(formData);
			happinessFormDataRepository.Save();

ClinicalStudy.Site/Areas/DataCapture/Controllers/VisitController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using ClinicalStudy.DomainModel;
using ClinicalStudy.DomainModel.Enums;
using ClinicalStudy.DomainModel.ModelBuilders;
using ClinicalStudy.Repositories.Interface;
using ClinicalStudy.Site.Areas.DataCapture.Models;
using ClinicalStudy.Site.Areas.DataCapture.Models.Shared;
using DevExpress.Web.Mvc;

namespace ClinicalStudy.Site.Areas.DataCapture.Controllers {
	public class VisitController : DataCaptureBaseController {
		private readonly IClinicalStudyDesignFactory clinicalStudyDesignFactory;
		private readonly IVisitRepository visitRepository;

		public VisitController(IVisitRepository visitRepository, IClinicalStudyDesignFactory clinicalStudyDesignFactory) {
			this.visitRepository = visitRepository;
			this.clinicalStudyDesignFactory = clinicalStudyDesignFactory;
		}

		public ActionResult VisitDataContainer(int patientNumber, string visitName, string formName) {
			DataContainerViewModel model = CreateVisitDataModel(patientNumber, visitName, formName);

			return PartialView("_VisitDataContainer", model);
		}

		private DataContainerViewModel CreateVisitDataModel(int patientNumber, string visitName, string formName) {
			Visit visit = visitRepository.GetVisitByPatientNumberAndVisitName(patientNumber, visitName);
			if (visit == null)
				return null;

			var model = new DataContainerViewModel {
				Id = visit.Id,
				PatientNumber = patientNumber,
				SelectedVisitName = visitName,
				SelectedFormName = formName,
				Children = new List<ConteinerChildViewModel>(from form in visit.Forms
				                                             orderby form.OrderNo
				                                             select new ConteinerChildViewModel {
				                                             	Id = form.Id,
				                                             	Caption = form.Caption,
				                                             	OrderNo = form.OrderNo
				                                             })
			};
			return model;
		}


		public ActionResult ShowVisit(int patientNumber, string visitName) {
			return ViewEditVisit(null, patientNumber, visitName);
		}

		public ActionResult ViewVisit(int patientNumber, string visitName) {
			return ViewEditVisit(false, patientNumber, visitName);
		}

		public ActionResult EditVisit(int visitId) {
			return ViewEditVisit(true, visitId);
		}

		public ActionResult ViewEditVisit(bool? isVisitEditing, int visitId) {
			Visit visit = visitRepository.GetByKey(visitId);
			return ViewEditVisit(isVisitEditing, visit);
		}

		public ActionResult ViewEditVisit(bool? isVisitEditing, int patientNumber, string visitName) {
			Visit visit = visitRepository.GetVisitByPatientNumberAndVisitName(patientNumber, visitName);
			return ViewEditVisit(isVisitEditing, visit);
		}


		private ActionResult ViewEditVisit(bool? isVisitEditing, Visit visit) {
			if (visit == null) {
				var errorModel = new ErrorViewModel {
					Caption = "Visit is not found",
					ErrorMessage = string.Format("Visit is not found in clinical data")
				};
				return View("ErrorInfo", errorModel);
			}

			var model = new VisitViewModel {
				Id = visit.Id,
				Caption = visit.Caption,
				VisitType = visit.VisitType,
				ExpectedVisitDate = visit.ExpectedVisitDate,
				VisitDate = visit.VisitDate,
				VisitTime = visit.VisitTime,
				OrderNo = visit.OrderNo,
				NoExpectedVisitDate = visit.VisitType == VisitType.AdverseEventVisit
			};

			if (visit.IsCompleted && !(isVisitEditing ?? false))
				return PartialView("_ViewVisit", model);
			return PartialView("_EditVisit", model);
		}

		[HttpPost]
		public ActionResult EditVisit([ModelBinder(typeof (DevExpressEditorsBinder))] VisitViewModel model) {
			Visit visit = visitRepository.GetByKey(model.Id);
			if (visit == null) {
				var errorModel = new ErrorViewModel {
					Caption = "Visit is not found",
					ErrorMessage = string.Format("Visit '{0}' is not found in clinical data", model.Caption)
				};
				return View("ErrorInfo", errorModel);
			}

			visit.Caption = model.Caption;
			visit.ExpectedVisitDate = model.ExpectedVisitDate;
			visit.VisitDate = model.VisitDate;
			visit.VisitTime = model.VisitTime;
			EnsureSqlServer2005Compatibility(visit);
			if (visit.VisitDate.HasValue && visit.VisitTime.HasValue)
				visit.IsCompleted = true;
			visitRepository.Edit(visit);
			visitRepository.Save();

			return RedirectToAction("ShowVisit",
				new {
					patientNumber = visit.Patient.PatientNumber,
					visitName = visit.Caption,
					DXScript = Request["DXScript"]
				});
		}

		public ActionResult CreateAdverseEvent(int patientId) {
			IClinicalStudyDesign studyDesign = clinicalStudyDesignFactory.Create();

			Visit aeVisit = studyDesign.AddAdverseEventVisit(patientId);
			clinicalStudyDesignFactory.Release(studyDesign);


			if (aeVisit == null)
				return null;


			return Content(aeVisit.Caption);
		}

		private static void EnsureSqlServer2005Compatibility(Visit visit) {
			if (visit.VisitTime.HasValue && visit.VisitTime.Value.Year <= 1753)
				visit.VisitTime = visit.VisitTime.Value.AddYears(DateTime.Now.Year);
		}
	}
}

ClinicalStudy.Site/Areas/DataCapture/Views/Visit/GetEditVisit.cshtml
@model ClinicalStudy.Site.Areas.DataCapture.Models.VisitViewModel

@{
	ViewBag.Title = "Edit Visit";
	Layout = "~/Areas/DataCapture/Views/Shared/_DataCaptureLayout.cshtml";
}

@Html.Partial("_EditVisit", Model)

ClinicalStudy.Site/Areas/DataCapture/Views/Visit/_EditVisit.cshtml
@model ClinicalStudy.Site.Areas.DataCapture.Models.VisitViewModel
@{
	string validationGroup = string.Format("visit{0}Validation", Model.Id);
}

<div id="visitContainer@(Model.Id)" class="visitPanel">
	<h2>Visit Information</h2>
	@using (Ajax.BeginForm("EditVisit", "Visit",
		new AjaxOptions {
			UpdateTargetId = "visitContainer" + Model.Id.ToString(),
			LoadingElementId = "loadingIndicator"
		})) {
		@Html.HiddenFor(model => model.Id)
		@Html.HiddenFor(model => model.Caption)
		@Html.HiddenFor(model => model.NoExpectedVisitDate)
		<div class="editor-field">
			@Html.DevExpress().Label(s => {
		                               	s.ControlStyle.CssClass = "editor-label";
		                               	s.Text = "Visit Date:";
		                               	s.AssociatedControlName = "VisitDate";
		                               }).GetHtml()
			@Html.DevExpress().DateEdit(s => {
		                                  	s.Name = "VisitDate";
		                                  	s.Width = 150;
                                            s.ShowModelErrors = true;
                                            s.Properties.ValidationSettings.ValidationGroup = validationGroup;
		                                  	s.Properties.ValidationSettings.ErrorDisplayMode = ErrorDisplayMode.ImageWithText;
		                                  }).Bind(Model.VisitDate).GetHtml()
		</div>
		<div class="editor-field">
			@Html.HiddenFor(model => model.Id)
			@Html.DevExpress().Label(s => {
		                               	s.ControlStyle.CssClass = "editor-label";
		                               	s.Text = "Visit Time:";
		                               	s.AssociatedControlName = "VisitTime";
		                               }).GetHtml()
			@Html.DevExpress().TimeEdit(s => {
		                                  	s.Name = "VisitTime";
		                                  	s.Width = 150;
                                            s.ShowModelErrors = true;
                                            s.Properties.ValidationSettings.ValidationGroup = validationGroup;
		                                  	s.Properties.ValidationSettings.ErrorDisplayMode = ErrorDisplayMode.ImageWithText;
		                                  }).Bind(Model.VisitTime).GetHtml()
		</div>
		if (!Model.NoExpectedVisitDate) {
			<div class="editor-field">
				@Html.HiddenFor(model => model.Id)
				@Html.DevExpress().Label(s => {
			                               	s.ControlStyle.CssClass = "editor-label";
			                               	s.Text = "Expected Visit Date:";
			                               	s.AssociatedControlName = "ExpectedVisitDate";
			                               }).GetHtml()
				@Html.DevExpress().DateEdit(s => {
			                                  	s.Name = "ExpectedVisitDate";
			                                  	s.Width = 150;
                                                s.ShowModelErrors = true;
                                                s.Properties.ValidationSettings.ValidationGroup = validationGroup;
			                                  	s.Properties.ValidationSettings.ErrorDisplayMode = ErrorDisplayMode.ImageWithText;
			                                  	s.ReadOnly = Model.NoExpectedVisitDate;
			                                  }).Bind(Model.ExpectedVisitDate).GetHtml()
			</div>
		}
		@Html.DevExpress().Button(s => {
		                                	s.Name = "btnSave_Visit" + Model.Id;
		                                	s.SkinID = "DarkPink";
		                                	s.Text = "Save";
		                                	s.UseSubmitBehavior = true;
		                                	s.ValidationGroup = validationGroup;
		                                }).GetHtml()
	}
</div>

ClinicalStudy.Site/Areas/DataCapture/Views/Visit/_ViewVisit.cshtml
@model ClinicalStudy.Site.Areas.DataCapture.Models.VisitViewModel
<div id="visitContainer@(Model.Id)" class="visitPanel">

	<h2 class="completed">Visit Information</h2>

	@Html.HiddenFor(model => model.Id)
	@Html.HiddenFor(model => model.Caption)
	<div class="editor-field">
		@Html.DevExpress().Label(s => {
	                               	s.ControlStyle.CssClass = "editor-label";
	                               	s.Text = "Visit Date:";
	                               	s.AssociatedControlName = "VisitDate";
	                               }).GetHtml()
		@Html.DevExpress().Label(s => {
	                               	s.Name = "VisitDate";
	                               	s.Width = 150;
	                               }).Bind(Model.VisitDate.HasValue ? Model.VisitDate.Value.ToShortDateString() : string.Empty).GetHtml()
	</div>
	<div class="editor-field">
		@Html.DevExpress().Label(s => {
	                               	s.ControlStyle.CssClass = "editor-label";
	                               	s.Text = "Visit Time:";
	                               	s.AssociatedControlName = "VisitTime";
	                               }).GetHtml()
    
		@Html.DevExpress().Label(s => {
	                               	s.Name = "VisitTime";
	                               	s.Width = 150;
	                               }).Bind(Model.VisitTime.Value.ToShortTimeString()).GetHtml()
	</div>
	@if (!Model.NoExpectedVisitDate) {
		<div class="editor-field">
			@Html.DevExpress().Label(s => {
		                               	s.ControlStyle.CssClass = "editor-label";
		                               	s.Text = "Expected Visit Date:";
		                               	s.AssociatedControlName = "ExpectedVisitDate";
		                               }).GetHtml()
			@Html.DevExpress().Label(s => {
		                               	s.Name = "ExpectedVisitDate";
		                               	s.Width = 150;
		                               }).Bind(Model.ExpectedVisitDate.HasValue ? Model.ExpectedVisitDate.Value.ToShortDateString() : string.Empty).GetHtml()
		</div>
	}
	@Html.DevExpress().Button(s => {
	                                	s.Name = "btnEditVisit";
	                                	s.SkinID = "Grey";
	                                	s.Text = "Edit";
                                	    s.CausesValidation = false;
	                                	string url = Url.Action("EditVisit", "Visit", new {Area = "DataCapture", visitId = Model.Id});

	                                	s.ClientSideEvents.Click = String.Format(@"function (s,e) {{
																				var ajaxOptions = {{UpdateTargetId : 'visitContainer{0}'}};
																				buttonAjaxClick(s,e, '{1}', ajaxOptions);}}",
											Model.Id, url);
	                                }).GetHtml()


</div>

ClinicalStudy.Site/Areas/DataCapture/Views/Visit/_VisitDataContainer.cshtml
@using ClinicalStudy.Site.Areas.DataCapture.Models.Shared
@model ClinicalStudy.Site.Areas.DataCapture.Models.Shared.DataContainerViewModel

@Html.Action("ShowVisit", "Visit", new {patientNumber = Model.PatientNumber, visitName = Model.SelectedVisitName})

@foreach (ConteinerChildViewModel child in Model.Children) {
	<div id="formPanel@(child.Id)" class="formPanel">
		@Html.Action("ShowForm", "Form", new {patientNumber = Model.PatientNumber, visitName = Model.SelectedVisitName, formName = child.Caption})
	</div>
}